# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rmstandem_wrappers", use_symbols = TRUE, package_name = "rmstandem")

#' @docType package
#' @usage NULL
#' @useDynLib rmstandem, .registration = TRUE
NULL

#' Return the mass of a peptide sequence
#' @export
peptide_mass <- function(s) .Call(wrap__peptide_mass, s)

#' Return the mass of an atom
#' @export
mass_atomic <- function(r) .Call(wrap__mass_atomic, r)

#' Return the mass of a proton
#' @export
mass_proton <- function() .Call(wrap__mass_proton)

#' Return the mass of a amino acid residue
#' @export
mass_residue <- function(s) .Call(wrap__mass_residue, s)

#' Return the length of a peptide sequence
#' @export
peptide_len <- function(s) .Call(wrap__peptide_len, s)

